// Multi-ported RAM Configuration File
// Generated by flow manager before logic synthesis
`define TYPE    "LVTBIN"	// Implementation: REG, XOR, LVTREG, LVTBIN, LVT1HT
`define BYP     "NON"		// Bypass: NON, WAW, RAW, RDW
`define MEMD    128		// RAM Depth (lines) 
`define DATAW   8		// Data Width (bits) 
`define nWPORTS 3		// Number of writing ports (>1)
`define nRPORTS 3		// Number of reading ports
